// Code generated by DI. DO NOT EDIT.

package decorators

import (
	"context"
	"reflect"

	"github.com/MaximZayats/godi/codegen"
	"github.com/MaximZayats/godi/di"
)

var Config = codegen.Config{
	PackageName:         "decorators",
	PathToStorageFolder: `./examples/storage/decorators`,
	StorageFileName:     "di_injection_decorators_gen.go",
	GetterFunction:      getDecorator,
}

var functions = map[string]any{

	"func(context.Context, int, string) int": func(f func(context.Context, int, string) int, c *di.Container) any {
		return func(a context.Context) int {
			return f(
				a,
				di.MustGetFromContainer[int](c), di.MustGetFromContainer[string](c),
			)
		}
	},

	"func(context.Context, int) int": func(f func(context.Context, int) int, c *di.Container) any {
		return func(a context.Context) int {
			return f(
				a,
				di.MustGetFromContainer[int](c),
			)
		}
	},
}

func getDecorator(f any) (any, bool) {
	v, ok := functions[reflect.TypeOf(f).String()]
	return v, ok
}
