package codegen

const fileTemplate = `
// Code generated by DI. DO NOT EDIT.

package {{ .config.PackageName }}

import (
	"github.com/MaximZayats/godi/codegen"
	"github.com/MaximZayats/godi/di"
	"reflect"
)

var Config = codegen.Config{
	PackageName:         "{{ .config.PackageName }}",
	PathToStorageFolder: ` + "`{{ .config.PathToStorageFolder }}`" + `,
	StorageFileName:     "{{ .config.StorageFileName }}",
	GetterFunction:      getDecorator,
}


var functions = map[string]any{
	{{ range $sig := .signatures }}
	"{{ $sig.FullSignature }}": func(f {{ $sig.FullSignature }}, c *di.Container) any {
		return {{ $sig.RequiredSignature }} {
			{{ if $sig.WithReturn }}return {{ end }}f(
				{{ range $argName := $sig.RequiredArgsNames }}{{ $argName }},{{ end }}
				{{ range $argType := $sig.ArgsTypesToGet }}di.MustGetFromContainer[{{ $argType }}](c),{{ end }}
			)
		}
	},
	{{ end }}
}

func getDecorator(f any) (any, bool) {
	v, ok := functions[reflect.TypeOf(f).String()]
	return v, ok
}

`
